-- Seed historical LeetCode problems.
-- Run with:
--   kubectl exec -i -n athena deploy/postgres -- psql -U athena -d athena < scripts/seed_leetcode.sql

INSERT INTO leetcode_problems (title, slug, difficulty, solved_at) VALUES
  ('Two Sum', 'two-sum', 'Easy', '2026-02-05'),
  ('Add Two Numbers', 'add-two-numbers', 'Medium', '2025-09-07'),
  ('Longest Substring Without Repeating Characters', 'longest-substring-without-repeating-characters', 'Medium', '2026-04-14'),
  ('Longest Palindromic Substring', 'longest-palindromic-substring', 'Medium', '2025-07-25'),
  ('Reverse Integer', 'reverse-integer', 'Medium', '2025-07-15'),
  ('Palindrome Number', 'palindrome-number', 'Easy', '2026-03-06'),
  ('Container With Most Water', 'container-with-most-water', 'Medium', '2025-07-22'),
  ('Integer to Roman', 'integer-to-roman', 'Medium', '2025-07-21'),
  ('Roman to Integer', 'roman-to-integer', 'Easy', '2026-05-23'),
  ('Longest Common Prefix', 'longest-common-prefix', 'Easy', '2026-05-18'),
  ('3Sum', '3sum', 'Medium', '2026-05-22'),
  ('3Sum Closest', '3sum-closest', 'Medium', '2025-04-25'),
  ('Letter Combinations of a Phone Number', 'letter-combinations-of-a-phone-number', 'Medium', '2026-05-22'),
  ('4Sum', '4sum', 'Medium', '2026-02-09'),
  ('Remove Nth Node From End of List', 'remove-nth-node-from-end-of-list', 'Medium', '2025-09-07'),
  ('Valid Parentheses', 'valid-parentheses', 'Easy', '2025-07-14'),
  ('Merge Two Sorted Lists', 'merge-two-sorted-lists', 'Easy', '2026-05-22'),
  ('Merge k Sorted Lists', 'merge-k-sorted-lists', 'Hard', '2026-04-19'),
  ('Remove Duplicates from Sorted Array', 'remove-duplicates-from-sorted-array', 'Easy', '2025-10-06'),
  ('Find the Index of the First Occurrence in a String', 'find-the-index-of-the-first-occurrence-in-a-string', 'Easy', '2026-06-09'),
  ('Next Permutation', 'next-permutation', 'Medium', '2026-05-21'),
  ('Search in Rotated Sorted Array', 'search-in-rotated-sorted-array', 'Medium', '2025-07-17'),
  ('Search Insert Position', 'search-insert-position', 'Easy', '2026-01-13'),
  ('Valid Sudoku', 'valid-sudoku', 'Medium', '2025-07-23'),
  ('Count and Say', 'count-and-say', 'Medium', '2026-05-22'),
  ('Combination Sum', 'combination-sum', 'Medium', '2026-05-22'),
  ('Combination Sum II', 'combination-sum-ii', 'Medium', '2026-05-21'),
  ('First Missing Positive', 'first-missing-positive', 'Hard', '2026-05-22'),
  ('Trapping Rain Water', 'trapping-rain-water', 'Hard', '2026-06-09'),
  ('Multiply Strings', 'multiply-strings', 'Medium', '2026-05-23'),
  ('Jump Game II', 'jump-game-ii', 'Medium', '2026-05-21'),
  ('Permutations', 'permutations', 'Medium', '2026-05-22'),
  ('Permutations II', 'permutations-ii', 'Medium', '2026-05-20'),
  ('Rotate Image', 'rotate-image', 'Medium', '2026-02-15'),
  ('Group Anagrams', 'group-anagrams', 'Medium', '2025-07-26'),
  ('Pow(x, n)', 'powx-n', 'Medium', '2026-04-27'),
  ('Maximum Subarray', 'maximum-subarray', 'Medium', '2026-05-20'),
  ('Spiral Matrix', 'spiral-matrix', 'Medium', '2026-05-25'),
  ('Jump Game', 'jump-game', 'Medium', '2025-09-22'),
  ('Permutation Sequence', 'permutation-sequence', 'Hard', '2026-05-05'),
  ('Rotate List', 'rotate-list', 'Medium', '2026-05-26'),
  ('Unique Paths', 'unique-paths', 'Medium', '2026-05-27'),
  ('Unique Paths II', 'unique-paths-ii', 'Medium', '2026-05-26'),
  ('Minimum Path Sum', 'minimum-path-sum', 'Medium', '2025-07-30'),
  ('Valid Number', 'valid-number', 'Hard', '2025-07-22'),
  ('Plus One', 'plus-one', 'Easy', '2026-02-07'),
  ('Sqrt(x)', 'sqrtx', 'Easy', '2026-05-21'),
  ('Climbing Stairs', 'climbing-stairs', 'Easy', '2026-05-26'),
  ('Edit Distance', 'edit-distance', 'Medium', '2026-05-20'),
  ('Set Matrix Zeroes', 'set-matrix-zeroes', 'Medium', '2026-05-21'),
  ('Search a 2D Matrix', 'search-a-2d-matrix', 'Medium', '2025-07-18'),
  ('Sort Colors', 'sort-colors', 'Medium', '2026-01-25'),
  ('Subsets', 'subsets', 'Medium', '2026-05-22'),
  ('Word Search', 'word-search', 'Medium', '2026-04-24'),
  ('Partition List', 'partition-list', 'Medium', '2026-04-24'),
  ('Gray Code', 'gray-code', 'Medium', '2026-01-25'),
  ('Subsets II', 'subsets-ii', 'Medium', '2026-05-26'),
  ('Decode Ways', 'decode-ways', 'Medium', '2025-10-07'),
  ('Binary Tree Inorder Traversal', 'binary-tree-inorder-traversal', 'Easy', '2026-05-27'),
  ('Unique Binary Search Trees II', 'unique-binary-search-trees-ii', 'Medium', '2026-05-27'),
  ('Unique Binary Search Trees', 'unique-binary-search-trees', 'Medium', '2026-05-26'),
  ('Interleaving String', 'interleaving-string', 'Medium', '2026-01-02'),
  ('Validate Binary Search Tree', 'validate-binary-search-tree', 'Medium', '2026-05-22'),
  ('Same Tree', 'same-tree', 'Easy', '2025-07-22'),
  ('Symmetric Tree', 'symmetric-tree', 'Easy', '2026-05-20'),
  ('Binary Tree Level Order Traversal', 'binary-tree-level-order-traversal', 'Medium', '2026-05-20'),
  ('Maximum Depth of Binary Tree', 'maximum-depth-of-binary-tree', 'Easy', '2026-06-09'),
  ('Construct Binary Tree from Preorder and Inorder Traversal', 'construct-binary-tree-from-preorder-and-inorder-traversal', 'Medium', '2026-04-13'),
  ('Convert Sorted Array to Binary Search Tree', 'convert-sorted-array-to-binary-search-tree', 'Easy', '2026-02-07'),
  ('Balanced Binary Tree', 'balanced-binary-tree', 'Easy', '2026-06-09'),
  ('Path Sum', 'path-sum', 'Easy', '2025-07-31'),
  ('Pascal''s Triangle', 'pascals-triangle', 'Easy', '2026-05-25'),
  ('Pascal''s Triangle II', 'pascals-triangle-ii', 'Easy', '2026-05-26'),
  ('Triangle', 'triangle', 'Medium', '2025-09-29'),
  ('Best Time to Buy and Sell Stock', 'best-time-to-buy-and-sell-stock', 'Easy', '2026-05-26'),
  ('Best Time to Buy and Sell Stock II', 'best-time-to-buy-and-sell-stock-ii', 'Medium', '2026-05-27'),
  ('Best Time to Buy and Sell Stock III', 'best-time-to-buy-and-sell-stock-iii', 'Hard', '2026-05-28'),
  ('Binary Tree Maximum Path Sum', 'binary-tree-maximum-path-sum', 'Hard', '2026-04-18'),
  ('Valid Palindrome', 'valid-palindrome', 'Easy', '2026-05-20'),
  ('Longest Consecutive Sequence', 'longest-consecutive-sequence', 'Medium', '2026-06-03'),
  ('Surrounded Regions', 'surrounded-regions', 'Medium', '2026-05-22'),
  ('Palindrome Partitioning', 'palindrome-partitioning', 'Medium', '2026-06-09'),
  ('Clone Graph', 'clone-graph', 'Medium', '2026-05-23'),
  ('Gas Station', 'gas-station', 'Medium', '2026-03-06'),
  ('Single Number', 'single-number', 'Easy', '2026-05-21'),
  ('Copy List with Random Pointer', 'copy-list-with-random-pointer', 'Medium', '2026-05-22'),
  ('Word Break', 'word-break', 'Medium', '2026-05-20'),
  ('Linked List Cycle', 'linked-list-cycle', 'Easy', '2026-05-28'),
  ('Reorder List', 'reorder-list', 'Medium', '2026-05-20'),
  ('Evaluate Reverse Polish Notation', 'evaluate-reverse-polish-notation', 'Medium', '2026-04-24'),
  ('Reverse Words in a String', 'reverse-words-in-a-string', 'Medium', '2026-05-25'),
  ('Maximum Product Subarray', 'maximum-product-subarray', 'Medium', '2026-05-21'),
  ('Find Minimum in Rotated Sorted Array', 'find-minimum-in-rotated-sorted-array', 'Medium', '2026-05-21'),
  ('Min Stack', 'min-stack', 'Medium', '2026-04-18'),
  ('One Edit Distance', 'one-edit-distance', 'Medium', '2026-04-18'),
  ('Compare Version Numbers', 'compare-version-numbers', 'Medium', '2026-04-10'),
  ('Majority Element', 'majority-element', 'Easy', '2026-04-18'),
  ('Largest Number', 'largest-number', 'Medium', '2026-02-15'),
  ('Reverse Bits', 'reverse-bits', 'Easy', '2026-06-09'),
  ('Number of 1 Bits', 'number-of-1-bits', 'Easy', '2026-05-21'),
  ('House Robber', 'house-robber', 'Medium', '2026-05-20'),
  ('Binary Tree Right Side View', 'binary-tree-right-side-view', 'Medium', '2026-06-01'),
  ('Number of Islands', 'number-of-islands', 'Medium', '2026-05-23'),
  ('Bitwise AND of Numbers Range', 'bitwise-and-of-numbers-range', 'Medium', '2026-02-01'),
  ('Happy Number', 'happy-number', 'Easy', '2026-05-23'),
  ('Reverse Linked List', 'reverse-linked-list', 'Easy', '2026-05-23'),
  ('Implement Trie (Prefix Tree)', 'implement-trie-prefix-tree', 'Medium', '2026-06-09'),
  ('Minimum Size Subarray Sum', 'minimum-size-subarray-sum', 'Medium', '2026-05-23'),
  ('Design Add and Search Words Data Structure', 'design-add-and-search-words-data-structure', 'Medium', '2026-05-23'),
  ('Word Search II', 'word-search-ii', 'Hard', '2026-05-21'),
  ('House Robber II', 'house-robber-ii', 'Medium', '2026-05-22'),
  ('Kth Largest Element in an Array', 'kth-largest-element-in-an-array', 'Medium', '2026-04-10'),
  ('Contains Duplicate', 'contains-duplicate', 'Easy', '2026-03-08'),
  ('Contains Duplicate II', 'contains-duplicate-ii', 'Easy', '2026-05-26'),
  ('Maximal Square', 'maximal-square', 'Medium', '2025-07-26'),
  ('Rectangle Area', 'rectangle-area', 'Medium', '2026-05-20'),
  ('Invert Binary Tree', 'invert-binary-tree', 'Easy', '2026-03-07'),
  ('Summary Ranges', 'summary-ranges', 'Easy', '2026-05-21'),
  ('Kth Smallest Element in a BST', 'kth-smallest-element-in-a-bst', 'Medium', '2026-02-01'),
  ('Power of Two', 'power-of-two', 'Easy', '2026-05-21'),
  ('Lowest Common Ancestor of a Binary Search Tree', 'lowest-common-ancestor-of-a-binary-search-tree', 'Medium', '2026-05-20'),
  ('Lowest Common Ancestor of a Binary Tree', 'lowest-common-ancestor-of-a-binary-tree', 'Medium', '2026-04-19'),
  ('Product of Array Except Self', 'product-of-array-except-self', 'Medium', '2026-02-15'),
  ('Valid Anagram', 'valid-anagram', 'Easy', '2025-07-17'),
  ('Meeting Rooms', 'meeting-rooms', 'Easy', '2026-02-01'),
  ('Add Digits', 'add-digits', 'Easy', '2026-05-23'),
  ('Single Number III', 'single-number-iii', 'Medium', '2026-06-08'),
  ('Graph Valid Tree', 'graph-valid-tree', 'Medium', '2026-02-01'),
  ('Ugly Number', 'ugly-number', 'Easy', '2025-07-17'),
  ('Missing Number', 'missing-number', 'Easy', '2026-05-21'),
  ('Perfect Squares', 'perfect-squares', 'Medium', '2026-04-10'),
  ('Move Zeroes', 'move-zeroes', 'Easy', '2026-05-20'),
  ('Find the Duplicate Number', 'find-the-duplicate-number', 'Medium', '2026-04-18'),
  ('Word Pattern', 'word-pattern', 'Easy', '2026-01-13'),
  ('Nim Game', 'nim-game', 'Easy', '2026-05-27'),
  ('Find Median from Data Stream', 'find-median-from-data-stream', 'Hard', '2026-05-23'),
  ('Serialize and Deserialize Binary Tree', 'serialize-and-deserialize-binary-tree', 'Hard', '2026-05-25'),
  ('Longest Increasing Subsequence', 'longest-increasing-subsequence', 'Medium', '2026-05-25'),
  ('Range Sum Query - Immutable', 'range-sum-query-immutable', 'Easy', '2026-05-17'),
  ('Coin Change', 'coin-change', 'Medium', '2026-06-08'),
  ('Number of Connected Components in an Undirected Graph', 'number-of-connected-components-in-an-undirected-graph', 'Medium', '2026-05-27'),
  ('House Robber III', 'house-robber-iii', 'Medium', '2026-05-22'),
  ('Counting Bits', 'counting-bits', 'Easy', '2026-04-18'),
  ('Reverse String', 'reverse-string', 'Easy', '2026-04-18'),
  ('Reverse Vowels of a String', 'reverse-vowels-of-a-string', 'Easy', '2026-04-19'),
  ('Top K Frequent Elements', 'top-k-frequent-elements', 'Medium', '2025-07-17'),
  ('Intersection of Two Arrays', 'intersection-of-two-arrays', 'Easy', '2026-05-26'),
  ('Largest Divisible Subset', 'largest-divisible-subset', 'Medium', '2026-05-21'),
  ('Sum of Two Integers', 'sum-of-two-integers', 'Medium', '2026-05-26'),
  ('Wiggle Subsequence', 'wiggle-subsequence', 'Medium', '2026-05-24'),
  ('Combination Sum IV', 'combination-sum-iv', 'Medium', '2025-07-17'),
  ('Find the Difference', 'find-the-difference', 'Easy', '2026-05-25'),
  ('Is Subsequence', 'is-subsequence', 'Easy', '2026-05-01'),
  ('Rotate Function', 'rotate-function', 'Medium', '2026-04-18'),
  ('Remove K Digits', 'remove-k-digits', 'Medium', '2026-04-18'),
  ('Convert a Number to Hexadecimal', 'convert-a-number-to-hexadecimal', 'Easy', '2026-05-23'),
  ('Add Strings', 'add-strings', 'Easy', '2026-05-22'),
  ('Partition Equal Subset Sum', 'partition-equal-subset-sum', 'Medium', '2026-05-20'),
  ('Find All Anagrams in a String', 'find-all-anagrams-in-a-string', 'Medium', '2026-05-29'),
  ('Delete Node in a BST', 'delete-node-in-a-bst', 'Medium', '2026-06-01'),
  ('Island Perimeter', 'island-perimeter', 'Easy', '2026-06-09'),
  ('Implement Rand10() Using Rand7()', 'implement-rand10-using-rand7', 'Medium', '2026-05-22'),
  ('Target Sum', 'target-sum', 'Medium', '2026-05-26'),
  ('Longest Palindromic Subsequence', 'longest-palindromic-subsequence', 'Medium', '2026-05-22'),
  ('Coin Change II', 'coin-change-ii', 'Medium', '2026-05-20'),
  ('Continuous Subarray Sum', 'continuous-subarray-sum', 'Medium', '2026-05-20'),
  ('Contiguous Array', 'contiguous-array', 'Medium', '2026-05-20'),
  ('Diameter of Binary Tree', 'diameter-of-binary-tree', 'Easy', '2026-06-05'),
  ('Number of Provinces', 'number-of-provinces', 'Medium', '2026-05-20'),
  ('Subarray Sum Equals K', 'subarray-sum-equals-k', 'Medium', '2026-05-22'),
  ('Find the Closest Palindrome', 'find-the-closest-palindrome', 'Hard', '2026-05-20'),
  ('Permutation in String', 'permutation-in-string', 'Medium', '2026-05-26'),
  ('Delete Operation for Two Strings', 'delete-operation-for-two-strings', 'Medium', '2025-09-26'),
  ('Valid Triangle Number', 'valid-triangle-number', 'Medium', '2026-05-31'),
  ('Task Scheduler', 'task-scheduler', 'Medium', '2026-05-25'),
  ('Decode Ways II', 'decode-ways-ii', 'Hard', '2026-04-27'),
  ('Maximum Average Subarray I', 'maximum-average-subarray-i', 'Easy', '2026-05-26'),
  ('Palindromic Substrings', 'palindromic-substrings', 'Medium', '2026-05-23'),
  ('Replace Words', 'replace-words', 'Medium', '2026-06-09'),
  ('Maximum Width of Binary Tree', 'maximum-width-of-binary-tree', 'Medium', '2026-05-26'),
  ('Number of Longest Increasing Subsequence', 'number-of-longest-increasing-subsequence', 'Medium', '2026-06-09'),
  ('Valid Parenthesis String', 'valid-parenthesis-string', 'Medium', '2026-06-08'),
  ('Redundant Connection', 'redundant-connection', 'Medium', '2026-06-01'),
  ('Employee Importance', 'employee-importance', 'Medium', '2026-06-01'),
  ('Max Area of Island', 'max-area-of-island', 'Medium', '2026-05-22'),
  ('Kth Largest Element in a Stream', 'kth-largest-element-in-a-stream', 'Easy', '2026-05-21'),
  ('Binary Search', 'binary-search', 'Easy', '2026-05-25'),
  ('Minimum ASCII Delete Sum for Two Strings', 'minimum-ascii-delete-sum-for-two-strings', 'Medium', '2026-05-25'),
  ('Maximum Length of Repeated Subarray', 'maximum-length-of-repeated-subarray', 'Medium', '2026-06-08'),
  ('Accounts Merge', 'accounts-merge', 'Medium', '2025-07-28'),
  ('Self Dividing Numbers', 'self-dividing-numbers', 'Easy', '2026-06-02'),
  ('Flood Fill', 'flood-fill', 'Easy', '2026-05-22'),
  ('Daily Temperatures', 'daily-temperatures', 'Medium', '2026-05-25'),
  ('Delete and Earn', 'delete-and-earn', 'Medium', '2026-06-08'),
  ('Network Delay Time', 'network-delay-time', 'Medium', '2026-02-01'),
  ('Find Smallest Letter Greater Than Target', 'find-smallest-letter-greater-than-target', 'Easy', '2026-05-25'),
  ('Min Cost Climbing Stairs', 'min-cost-climbing-stairs', 'Easy', '2026-06-09'),
  ('Cheapest Flights Within K Stops', 'cheapest-flights-within-k-stops', 'Medium', '2026-05-26'),
  ('Preimage Size of Factorial Zeroes Function', 'preimage-size-of-factorial-zeroes-function', 'Hard', '2026-05-02'),
  ('Rotate String', 'rotate-string', 'Easy', '2026-06-02'),
  ('Find Eventual Safe States', 'find-eventual-safe-states', 'Medium', '2025-07-29'),
  ('Consecutive Numbers Sum', 'consecutive-numbers-sum', 'Hard', '2026-06-01'),
  ('Keys and Rooms', 'keys-and-rooms', 'Medium', '2026-05-21'),
  ('Koko Eating Bananas', 'koko-eating-bananas', 'Medium', '2026-05-26'),
  ('Stone Game', 'stone-game', 'Medium', '2025-07-30'),
  ('Super Palindromes', 'super-palindromes', 'Hard', '2026-06-02'),
  ('Snakes and Ladders', 'snakes-and-ladders', 'Medium', '2026-01-25'),
  ('Word Subsets', 'word-subsets', 'Medium', '2026-05-26'),
  ('Minimum Falling Path Sum', 'minimum-falling-path-sum', 'Medium', '2026-01-02'),
  ('N-Repeated Element in Size 2N Array', 'n-repeated-element-in-size-2n-array', 'Easy', '2026-05-22'),
  ('K Closest Points to Origin', 'k-closest-points-to-origin', 'Medium', '2026-05-20'),
  ('Squares of a Sorted Array', 'squares-of-a-sorted-array', 'Easy', '2026-05-25'),
  ('Longest Turbulent Subarray', 'longest-turbulent-subarray', 'Medium', '2026-06-01'),
  ('Rotting Oranges', 'rotting-oranges', 'Medium', '2026-06-01'),
  ('Find the Town Judge', 'find-the-town-judge', 'Easy', '2026-05-25'),
  ('Divisor Game', 'divisor-game', 'Easy', '2026-06-02'),
  ('Coloring A Border', 'coloring-a-border', 'Medium', '2026-05-25'),
  ('Uncrossed Lines', 'uncrossed-lines', 'Medium', '2026-06-05'),
  ('Longest String Chain', 'longest-string-chain', 'Medium', '2026-06-02'),
  ('Shortest Path in Binary Matrix', 'shortest-path-in-binary-matrix', 'Medium', '2026-05-25'),
  ('N-th Tribonacci Number', 'n-th-tribonacci-number', 'Easy', '2026-05-26'),
  ('Longest Common Subsequence', 'longest-common-subsequence', 'Medium', '2026-01-06'),
  ('Maximum Level Sum of a Binary Tree', 'maximum-level-sum-of-a-binary-tree', 'Medium', '2026-01-14'),
  ('Airplane Seat Assignment Probability', 'airplane-seat-assignment-probability', 'Medium', '2026-05-27'),
  ('Minimum Remove to Make Valid Parentheses', 'minimum-remove-to-make-valid-parentheses', 'Medium', '2025-08-19'),
  ('Count Square Submatrices with All Ones', 'count-square-submatrices-with-all-ones', 'Medium', '2025-07-13'),
  ('Convert Binary Number in a Linked List to Integer', 'convert-binary-number-in-a-linked-list-to-integer', 'Easy', '2025-09-07'),
  ('Find N Unique Integers Sum up to Zero', 'find-n-unique-integers-sum-up-to-zero', 'Easy', '2026-06-03'),
  ('Jump Game III', 'jump-game-iii', 'Medium', '2026-06-03'),
  ('Jump Game IV', 'jump-game-iv', 'Hard', '2025-12-28'),
  ('Count Negative Numbers in a Sorted Matrix', 'count-negative-numbers-in-a-sorted-matrix', 'Easy', '2026-03-06'),
  ('Rank Teams by Votes', 'rank-teams-by-votes', 'Medium', '2026-05-27'),
  ('Longest ZigZag Path in a Binary Tree', 'longest-zigzag-path-in-a-binary-tree', 'Medium', '2026-06-02'),
  ('Time Needed to Inform All Employees', 'time-needed-to-inform-all-employees', 'Medium', '2026-01-04'),
  ('Four Divisors', 'four-divisors', 'Medium', '2026-06-09'),
  ('Count Good Nodes in Binary Tree', 'count-good-nodes-in-binary-tree', 'Medium', '2026-05-18'),
  ('Running Sum of 1d Array', 'running-sum-of-1d-array', 'Easy', '2026-06-08'),
  ('Path with Maximum Probability', 'path-with-maximum-probability', 'Medium', '2025-10-02'),
  ('Water Bottles', 'water-bottles', 'Easy', '2026-06-03'),
  ('Number of Nodes in the Sub-Tree With the Same Label', 'number-of-nodes-in-the-sub-tree-with-the-same-label', 'Medium', '2025-07-27'),
  ('Three Consecutive Odds', 'three-consecutive-odds', 'Easy', '2026-06-01'),
  ('Minimum Number of Vertices to Reach All Nodes', 'minimum-number-of-vertices-to-reach-all-nodes', 'Medium', '2026-06-08'),
  ('Min Cost to Connect All Points', 'min-cost-to-connect-all-points', 'Medium', '2026-05-26'),
  ('Count Substrings That Differ by One Character', 'count-substrings-that-differ-by-one-character', 'Medium', '2026-05-27'),
  ('Maximum Score from Performing Multiplication Operations', 'maximum-score-from-performing-multiplication-operations', 'Hard', '2026-06-01'),
  ('Find Center of Star Graph', 'find-center-of-star-graph', 'Easy', '2026-01-30'),
  ('Sum of All Subset XOR Totals', 'sum-of-all-subset-xor-totals', 'Easy', '2026-06-01'),
  ('Count Sub Islands', 'count-sub-islands', 'Medium', '2026-04-10'),
  ('Build Array from Permutation', 'build-array-from-permutation', 'Easy', '2026-06-01'),
  ('Nearest Exit from Entrance in Maze', 'nearest-exit-from-entrance-in-maze', 'Medium', '2026-04-10'),
  ('Concatenation of Array', 'concatenation-of-array', 'Easy', '2025-09-15'),
  ('Maximum Number of Words You Can Type', 'maximum-number-of-words-you-can-type', 'Easy', '2026-06-01'),
  ('Find if Path Exists in Graph', 'find-if-path-exists-in-graph', 'Easy', '2026-01-04'),
  ('Maximum Matrix Sum', 'maximum-matrix-sum', 'Medium', '2026-06-09'),
  ('Number of Ways to Arrive at Destination', 'number-of-ways-to-arrive-at-destination', 'Medium', '2026-01-25'),
  ('Minimum Difference Between Highest and Lowest of K Scores', 'minimum-difference-between-highest-and-lowest-of-k-scores', 'Easy', '2026-06-09'),
  ('Find the Kth Largest Integer in the Array', 'find-the-kth-largest-integer-in-the-array', 'Medium', '2026-05-30'),
  ('Destroying Asteroids', 'destroying-asteroids', 'Medium', '2025-09-22'),
  ('Maximum Good People Based on Statements', 'maximum-good-people-based-on-statements', 'Hard', '2025-07-23'),
  ('Count Equal and Divisible Pairs in an Array', 'count-equal-and-divisible-pairs-in-an-array', 'Easy', '2025-07-27'),
  ('Count Hills and Valleys in an Array', 'count-hills-and-valleys-in-an-array', 'Easy', '2025-08-13'),
  ('Largest 3-Same-Digit Number in String', 'largest-3-same-digit-number-in-string', 'Easy', '2025-07-27'),
  ('Partition Array Such That Maximum Difference Is K', 'partition-array-such-that-maximum-difference-is-k', 'Medium', '2025-10-08'),
  ('Successful Pairs of Spells and Potions', 'successful-pairs-of-spells-and-potions', 'Medium', '2026-06-03'),
  ('Reachable Nodes With Restrictions', 'reachable-nodes-with-restrictions', 'Medium', '2026-01-14'),
  ('Strictly Palindromic Number', 'strictly-palindromic-number', 'Medium', '2026-01-13'),
  ('Longest Subarray With Maximum Bitwise AND', 'longest-subarray-with-maximum-bitwise-and', 'Medium', '2026-01-13'),
  ('Bitwise XOR of All Pairings', 'bitwise-xor-of-all-pairings', 'Medium', '2025-12-30'),
  ('Minimum Penalty for a Shop', 'minimum-penalty-for-a-shop', 'Medium', '2026-04-14'),
  ('Shortest Distance to Target String in a Circular Array', 'shortest-distance-to-target-string-in-a-circular-array', 'Easy', '2026-05-11'),
  ('Separate the Digits in an Array', 'separate-the-digits-in-an-array', 'Easy', '2026-01-14'),
  ('Construct the Longest New String', 'construct-the-longest-new-string', 'Medium', '2026-03-30'),
  ('Check if Strings Can be Made Equal With Operations II', 'check-if-strings-can-be-made-equal-with-operations-ii', 'Medium', '2025-07-27'),
  ('Divide Array Into Arrays With Max Difference', 'divide-array-into-arrays-with-max-difference', 'Medium', '2026-03-06'),
  ('Minimum Operations to Write the Letter Y on a Grid', 'minimum-operations-to-write-the-letter-y-on-a-grid', 'Medium', '2025-10-02'),
  ('Water Bottles II', 'water-bottles-ii', 'Medium', '2025-07-14'),
  ('Valid Word', 'valid-word', 'Easy', '2026-01-13'),
  ('Vowels Game in a String', 'vowels-game-in-a-string', 'Medium', '2025-07-03'),
  ('Find the K-th Character in String Game I', 'find-the-k-th-character-in-string-game-i', 'Easy', '2025-07-03'),
  ('Find the K-th Character in String Game II', 'find-the-k-th-character-in-string-game-ii', 'Hard', '2025-07-13'),
  ('Find the Original Typed String I', 'find-the-original-typed-string-i', 'Easy', '2025-10-14'),
  ('Adjacent Increasing Subarrays Detection I', 'adjacent-increasing-subarrays-detection-i', 'Easy', '2026-02-05'),
  ('Transformed Array', 'transformed-array', 'Easy', '2025-10-19'),
  ('Check If Digits Are Equal in String After Operations I', 'check-if-digits-are-equal-in-string-after-operations-i', 'Easy', '2025-09-19'),
  ('Design Spreadsheet', 'design-spreadsheet', 'Medium', '2025-07-27'),
  ('Maximum Unique Subarray Sum After Deletion', 'maximum-unique-subarray-sum-after-deletion', 'Easy', '2026-04-18'),
  ('Mirror Distance of an Integer', 'mirror-distance-of-an-integer', 'Easy', '2026-06-09')
ON CONFLICT (slug) DO UPDATE
  SET difficulty = EXCLUDED.difficulty,
      solved_at  = EXCLUDED.solved_at;

-- Problems already in the DB from the first poll (20 most recent) will be
-- updated in place; all others are inserted fresh.
-- The nightly process job will only analyze the 20 most recent via the queue.
-- To bulk-queue everything for analysis, run:
--
--   INSERT INTO leetcode_queue (problem_slug, submitted_at, queued_at)
--   SELECT slug, solved_at, now() FROM leetcode_problems
--   ON CONFLICT (problem_slug) DO NOTHING;
